# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160312_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='title', null=True),
            preserve_default=False,
        ),
    ]
