# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 17:40
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify

def gen_slug(apps, schema_editor):
    MyModel = apps.get_model('posts', 'Post')
    for row in MyModel.objects.all():
    	row.slug = slugify(row.title)
    	row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_slug'),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop)
    ]
