# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_populate_slug_20160312_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='title', unique=True),
            preserve_default=False,
        ),
    ]
